add missing funcs for th client
GetThematic/ClientSDK pull request #27
Opened 2021-10-28 03:31 UTC by kvarekamp

this pr adds funcs to the client sdk that are needed for the th client. They are currently injected into the sdk at runtime:

```
from thematic_client_sdk.data import Data
Data.download_concepts = download_concepts
Data.upload_concepts = upload_concepts
...

```
Which is a bit messy. Some of these may be useful for others too

I do think there are some admin only restrictions on some of these funcs but not sure which ones. If we merge this PR, prob best to properly document that?

2021-10-28 06:28 UTC, nshgraph requested changes

2021-10-28 06:28 UTC, nshgraph commented on thematic_client_sdk/data.py
> +    def upload_data(self, survey_id, file_location, job_type):
This seems to be the same as the first function in the file? (see line 7)

2021-10-28 06:28 UTC, nshgraph commented on thematic_client_sdk/data.py
> +    def download_upload(self, survey_id, download_location, upload_id, unconverted):
This is in upload.py named  get_input()

2021-10-28 06:28 UTC, nshgraph commented on thematic_client_sdk/data.py
> +    def get_upload_status(self, survey_id, upload_id):
All the functions with upload_id as a parameter should really go in upload.py

2021-11-01 02:29 UTC, sockfish commented on thematic_client_sdk/data.py
> +    def upload_data(self, survey_id, file_location, job_type):
yes - removed

2021-11-01 02:30 UTC, sockfish commented on thematic_client_sdk/data.py
> +    def download_upload(self, survey_id, download_location, upload_id, unconverted):
yes, removed

2021-11-01 02:30 UTC, sockfish commented on thematic_client_sdk/data.py
> +    def get_upload_status(self, survey_id, upload_id):
moved (and renamed) all upload related funcs to upload_jobs.py

2023-04-05 22:09 UTC, closed without merging